---
title: "ISFG 2024 Workshop:<br>Kinship Statistics and Pedigree Analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{"ISFG Congress 2024 - Pre-congress workshop"}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      fig.align = "center",
                      collapse = TRUE,
                      comment = "#>")
```

* Date: Tuesday, 10th of September, 2024
* Where: San Francisco Hotel Monumento, Santiago de Compostela, Spain
* Teachers: Magnus Dehli Vigeland and Thore Egeland
* Pre-congress workshops: https://isfg2024.com/pre-congress-workshops/

## Description
The study of pedigrees and genetic relatedness is central in forensic genetics. The
aim of this course is to introduce the elegant statistical foundations of relatedness, as
well as several forensic applications. In certain parts we use R for calculations and
visualisations. In the basic session we will focus on pedigree coefficients and
likelihood ratios for kinship analysis. In addition, we will demonstrate QuickPed, an
online tool for creating pedigrees and computing relatedness: https://magnusdv.shinyapps.io/quickped

In the advanced part we will explore recently developed methods and implementations for Disaster Victim Identification (DVI) and pedigree reconstruction. 

The course material is based on the book [Pedigree Analysis in R](https://www.elsevier.com/books/pedigree-analysis-in-r/vigeland/978-0-12-824430-2) (Vigeland '21) and selected papers. Each session will alternate between lectures and hands-on
exercises. Solutions for all exercises will be provided and discussed at the end of each session.

Attendance in the ‘Basic session’ is not required for the ‘Advanced session’ for participants who are familiar with R.


## Learning outcome
After completing the course the participants will have knowledge about:

* Classical concepts of statistical genetics and relatedness analysis
* How to produce informative and beautiful pedigree plots
* How to compute coefficients of relatedness
* How to perform kinship testing and pedigree reconstruction in R
* How to perform disaster victim identification in R

## Prerequisites
* Basic knowledge of genetics and probability
* All participants must bring a laptop with administrative rights
* A recent version of [R](https://www.r-project.org) (at least 4.1) must be installed on your computer
* Some previous experience with R is recommended, but not strictly required
* We strongly recommend running R from [RStudio](https://www.rstudio.com/products/rstudio/download/)


## Schedule
The workshop is run as a full-day course on Tuesday 10th, from 9 to 18:30 (CEST). The following schedule is tentative:

#### Morning session -- Pedigree analysis: Basic
* 09:00--10:00 Lecture 1. [**Pedigrees and measures of relatedness**](https://github.com/magnusdv/pedsuite/blob/master/vignettes/web_only/courses/isfg2024/Lecture1_pedigrees.pdf) (MDV)
* 10:00--11:00 [Exercise set 1](https://github.com/magnusdv/pedsuite/blob/master/vignettes/web_only/courses/isfg2024/exercises1.pdf)
* 11:00--11:15 _Break_
* 11:15--12:00 Lecture 2. [**Kinship testing**](https://github.com/magnusdv/pedsuite/blob/master/vignettes/web_only/courses/isfg2024/Lecture2_kinship.pdf) (TE)
* 12:00--12:45 [Exercise set 2](https://github.com/magnusdv/pedsuite/blob/master/vignettes/web_only/courses/isfg2024/exercises2.pdf)
* 12:45--13:00 Summary and discussion  


<p style="text-indent: 12px;">**Lunch break 13:00 - 14:30**</p>

#### Afternoon session -- Pedigree analysis: Advanced
* 14:30--15:30 Lecture 3. [**Relatedness inference and pedigree reconstruction**](https://github.com/magnusdv/pedsuite/blob/master/vignettes/web_only/courses/isfg2023/Lecture3_reconstruction.pdf) (MDV)
* 15:30--16:15 [Exercise set 3](https://github.com/magnusdv/pedsuite/blob/master/vignettes/web_only/courses/isfg2023/exercises3.pdf)
* 16:15--16:30 _Break_
* 16:30--17:30 Lecture 4. [**Disaster victim identification**](https://github.com/magnusdv/pedsuite/blob/master/vignettes/web_only/courses/isfg2023/Lecture4_DVI.pdf) (TE)
* 17:30--18:15 [Exercise set 4](https://github.com/magnusdv/pedsuite/blob/master/vignettes/web_only/courses/isfg2023/exercises4.pdf)
* 18:15--18:30 Summary and discussion



Comments and questions may be sent to *magnusdv at gmail dot com*.
