---
title: ISFG Summer School - Virtual Edition 2021
subtitle: "Workshop 7: Pedigree analysis in R"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{ISFG Summer School - Virtual Edition 2021}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      fig.align = "center",
                      collapse = TRUE,
                      comment = "#>")
```

* Title: Pedigree analysis in R
* Dates: July 28-30, 2021
* Where: Online, as part of [ISFG Summer School 2021](https://isfgsummerschool.events.idloom.com/virtual-edition-2021)
* Teachers: Magnus Dehli Vigeland (MDV) and Thore Egeland (TE)

## Description
The study of genetic relatedness and how genetic information flows in families, is central in a variety of important research fields, including medical and forensic genetics. The aim of this course is to introduce the elegant concepts and results forming the theoretical foundation of genetic relatedness, and to present several forensic applications. Most lectures and exercises will based on the book [Pedigree Analysis in R](https://www.elsevier.com/books/pedigree-analysis-in-r/vigeland/978-0-12-824430-2). A 30% discount will be available for participants (but you do not have to buy the book in order to attend the course).

## Learning outcome
After completing the course, the participants should have knowledge about:

* Classical concepts and methods of statistical genetics and relatedness analysis
* How to create, manipulate and plot pedigrees in R
* How to compute pedigree likelihoods and likelihood ratios in R 
* How to perform kinship testing and pedigree reconstruction in R
* How to perform disaster victim identification in R

## Prerequisites
Basic knowledge of genetics and probability. All participants should have a laptop with R (version > 4.0) installed (available from www.r-project.org). The participants are assumed to have a basic knowledge of R.

## Schedule
The course runs from 14 to 18 (CEST) each day, with a 15 minutes break in the middle. The lectures are aimed at 55 minutes, allowing for a short interval before exercises.

#### Day 1 — July 28 (Wednesday)
* 14:00–15:00 **Lecture 1. Introduction I: Pedigrees, genetics and probabilities** (MDV)
* 15:00–15:45 Exercises
* 15:45–16:00 Break
* 16:00–17:00 **Lecture 2. Introduction II: Pedigrees analysis in R with the ped suite** (MDV)
* 17:00–18:00 Exercises

#### Day 2 — July 29 (Thursday)
* 14:00–15:00 **Lecture 3. Kinship testing LR: paternity cases and complex cases** (TE)
* 15:00–15:45 Exercises
* 15:45–16:00 Break
* 16:00–17:00 **Lecture 4. Relatedness coefficients and inference** (MDV)
* 17:00–18:00 Exercises

#### Day 3 — July 30 (Friday)
* 14:00–15:00 **Lecture 5. Pedigree reconstruction** (MDV)
* 15:00–15:45 Exercises
* 15:45–16:00 Break
* 16:00–17:00 **Lecture 6. Disaster victim identification and other forensic applications** (TE)
* 17:00–18:00 Exercises and wrap-up
  
  
Comments and questions may be sent to *magnusdv at gmail dot com*.
